use cardb;

CREATE TABLE IF NOT EXISTS t_driver (
  id      INT(10) NOT NULL AUTO_INCREMENT,
  phone   VARCHAR(16) NOT NULL,
  dev     VARCHAR(32) NOT NULL,
  name    VARCHAR(16) NOT NULL,
  image   VARCHAR(256) NOT NULL,
  license VARCHAR(16) NOT NULL,
  carno   VARCHAR(16) NOT NULL, 
  status  INT(2) NOT NULL,
  from_city VARCHAR(32) NOT NULL,
  to_city   VARCHAR(32) NOT NULL,
  priority  INT(10) NOT NULL,
  dt      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX (phone)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS t_driver_info (
  id      INT(10) NOT NULL,
  phone   VARCHAR(16) NOT NULL,
  name    VARCHAR(16) NOT NULL,
  image   VARCHAR(256) NOT NULL,
  license VARCHAR(16) NOT NULL,
  carno   VARCHAR(16) NOT NULL, 
  dt      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX (phone)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS t_driver_credit (
  id      INT(10) NOT NULL AUTO_INCREMENT,
  phone   VARCHAR(16) NOT NULL,
  credit  INT(10) NOT NULL,
  dt      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id) 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS t_poolorder (
  id          INT(10) NOT NULL AUTO_INCREMENT,
  po_id       VARCHAR(36) NOT NULL,
  po_type     INT(2) NOT NULL,
  status      INT(2) NOT NULL,
  price       FLOAT(6,3) NOT NULL,
  phone       VARCHAR(16) NOT NULL,
  from_city   VARCHAR(32) NOT NULL,
  to_city     VARCHAR(32) NOT NULL,
  orders      VARCHAR(256) NOT NULL,
  subsidy     FLOAT(6,3) NOT NULL,
  sstype      INT(2) NOT NULL,
  last_modify TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  dt          TIMESTAMP NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

