/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef order_TYPES_H
#define order_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace scheduler {

class Path;

class Order;

class Driver;

class HistoryDriver;

class PoolOrder;

class Message;

typedef struct _Path__isset {
  _Path__isset() : from_city(false), from_place(false), to_city(false), to_place(false), from_lat(false), from_lng(false), to_lat(false), to_lng(false) {}
  bool from_city :1;
  bool from_place :1;
  bool to_city :1;
  bool to_place :1;
  bool from_lat :1;
  bool from_lng :1;
  bool to_lat :1;
  bool to_lng :1;
} _Path__isset;

class Path {
 public:

  static const char* ascii_fingerprint; // = "245F00F9E4A5B0CEA9EB39A7B2A82616";
  static const uint8_t binary_fingerprint[16]; // = {0x24,0x5F,0x00,0xF9,0xE4,0xA5,0xB0,0xCE,0xA9,0xEB,0x39,0xA7,0xB2,0xA8,0x26,0x16};

  Path(const Path&);
  Path& operator=(const Path&);
  Path() : from_city(), from_place(), to_city(), to_place(), from_lat(0), from_lng(0), to_lat(0), to_lng(0) {
  }

  virtual ~Path() throw();
  std::string from_city;
  std::string from_place;
  std::string to_city;
  std::string to_place;
  double from_lat;
  double from_lng;
  double to_lat;
  double to_lng;

  _Path__isset __isset;

  void __set_from_city(const std::string& val);

  void __set_from_place(const std::string& val);

  void __set_to_city(const std::string& val);

  void __set_to_place(const std::string& val);

  void __set_from_lat(const double val);

  void __set_from_lng(const double val);

  void __set_to_lat(const double val);

  void __set_to_lng(const double val);

  bool operator == (const Path & rhs) const
  {
    if (!(from_city == rhs.from_city))
      return false;
    if (!(from_place == rhs.from_place))
      return false;
    if (!(to_city == rhs.to_city))
      return false;
    if (!(to_place == rhs.to_place))
      return false;
    if (!(from_lat == rhs.from_lat))
      return false;
    if (!(from_lng == rhs.from_lng))
      return false;
    if (!(to_lat == rhs.to_lat))
      return false;
    if (!(to_lng == rhs.to_lng))
      return false;
    return true;
  }
  bool operator != (const Path &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Path & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Path& obj);
};

void swap(Path &a, Path &b);

typedef struct _Order__isset {
  _Order__isset() : id(false), path(false), phone(false), number(false), cartype(false), price(false), time(false) {}
  bool id :1;
  bool path :1;
  bool phone :1;
  bool number :1;
  bool cartype :1;
  bool price :1;
  bool time :1;
} _Order__isset;

class Order {
 public:

  static const char* ascii_fingerprint; // = "0E95B2698AD9772974A275159CF76313";
  static const uint8_t binary_fingerprint[16]; // = {0x0E,0x95,0xB2,0x69,0x8A,0xD9,0x77,0x29,0x74,0xA2,0x75,0x15,0x9C,0xF7,0x63,0x13};

  Order(const Order&);
  Order& operator=(const Order&);
  Order() : id(0), phone(), number(0), cartype(0), price(0), time(0) {
  }

  virtual ~Order() throw();
  int64_t id;
  Path path;
  std::string phone;
  int32_t number;
  int32_t cartype;
  double price;
  int64_t time;

  _Order__isset __isset;

  void __set_id(const int64_t val);

  void __set_path(const Path& val);

  void __set_phone(const std::string& val);

  void __set_number(const int32_t val);

  void __set_cartype(const int32_t val);

  void __set_price(const double val);

  void __set_time(const int64_t val);

  bool operator == (const Order & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(path == rhs.path))
      return false;
    if (!(phone == rhs.phone))
      return false;
    if (!(number == rhs.number))
      return false;
    if (!(cartype == rhs.cartype))
      return false;
    if (!(price == rhs.price))
      return false;
    if (!(time == rhs.time))
      return false;
    return true;
  }
  bool operator != (const Order &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Order & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Order& obj);
};

void swap(Order &a, Order &b);

typedef struct _Driver__isset {
  _Driver__isset() : phone(false), priority(false) {}
  bool phone :1;
  bool priority :1;
} _Driver__isset;

class Driver {
 public:

  static const char* ascii_fingerprint; // = "EEBC915CE44901401D881E6091423036";
  static const uint8_t binary_fingerprint[16]; // = {0xEE,0xBC,0x91,0x5C,0xE4,0x49,0x01,0x40,0x1D,0x88,0x1E,0x60,0x91,0x42,0x30,0x36};

  Driver(const Driver&);
  Driver& operator=(const Driver&);
  Driver() : phone(), priority(0) {
  }

  virtual ~Driver() throw();
  std::string phone;
  int32_t priority;

  _Driver__isset __isset;

  void __set_phone(const std::string& val);

  void __set_priority(const int32_t val);

  bool operator == (const Driver & rhs) const
  {
    if (!(phone == rhs.phone))
      return false;
    if (!(priority == rhs.priority))
      return false;
    return true;
  }
  bool operator != (const Driver &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Driver & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Driver& obj);
};

void swap(Driver &a, Driver &b);

typedef struct _HistoryDriver__isset {
  _HistoryDriver__isset() : drivers(false), reduced(true), update_time(false) {}
  bool drivers :1;
  bool reduced :1;
  bool update_time :1;
} _HistoryDriver__isset;

class HistoryDriver {
 public:

  static const char* ascii_fingerprint; // = "386F45436DBA0A499AA232A1080C0B92";
  static const uint8_t binary_fingerprint[16]; // = {0x38,0x6F,0x45,0x43,0x6D,0xBA,0x0A,0x49,0x9A,0xA2,0x32,0xA1,0x08,0x0C,0x0B,0x92};

  HistoryDriver(const HistoryDriver&);
  HistoryDriver& operator=(const HistoryDriver&);
  HistoryDriver() : reduced(false), update_time(0) {
  }

  virtual ~HistoryDriver() throw();
  std::set<std::string>  drivers;
  bool reduced;
  int64_t update_time;

  _HistoryDriver__isset __isset;

  void __set_drivers(const std::set<std::string> & val);

  void __set_reduced(const bool val);

  void __set_update_time(const int64_t val);

  bool operator == (const HistoryDriver & rhs) const
  {
    if (!(drivers == rhs.drivers))
      return false;
    if (!(reduced == rhs.reduced))
      return false;
    if (!(update_time == rhs.update_time))
      return false;
    return true;
  }
  bool operator != (const HistoryDriver &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HistoryDriver & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const HistoryDriver& obj);
};

void swap(HistoryDriver &a, HistoryDriver &b);

typedef struct _PoolOrder__isset {
  _PoolOrder__isset() : id(false), cartype(false), order_list(false), pushtime(false), drivers(false), subsidy(true), sstype(true), number(false) {}
  bool id :1;
  bool cartype :1;
  bool order_list :1;
  bool pushtime :1;
  bool drivers :1;
  bool subsidy :1;
  bool sstype :1;
  bool number :1;
} _PoolOrder__isset;

class PoolOrder {
 public:

  static const char* ascii_fingerprint; // = "F7EEE70CFF3D3DDD7AC01476ABEC0F05";
  static const uint8_t binary_fingerprint[16]; // = {0xF7,0xEE,0xE7,0x0C,0xFF,0x3D,0x3D,0xDD,0x7A,0xC0,0x14,0x76,0xAB,0xEC,0x0F,0x05};

  PoolOrder(const PoolOrder&);
  PoolOrder& operator=(const PoolOrder&);
  PoolOrder() : id(), cartype(0), pushtime(0), subsidy(0), sstype(0), number(0) {
  }

  virtual ~PoolOrder() throw();
  std::string id;
  int32_t cartype;
  std::vector<Order>  order_list;
  int64_t pushtime;
  std::vector<Driver>  drivers;
  double subsidy;
  int32_t sstype;
  int32_t number;

  _PoolOrder__isset __isset;

  void __set_id(const std::string& val);

  void __set_cartype(const int32_t val);

  void __set_order_list(const std::vector<Order> & val);

  void __set_pushtime(const int64_t val);

  void __set_drivers(const std::vector<Driver> & val);

  void __set_subsidy(const double val);

  void __set_sstype(const int32_t val);

  void __set_number(const int32_t val);

  bool operator == (const PoolOrder & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(cartype == rhs.cartype))
      return false;
    if (!(order_list == rhs.order_list))
      return false;
    if (!(pushtime == rhs.pushtime))
      return false;
    if (!(drivers == rhs.drivers))
      return false;
    if (!(subsidy == rhs.subsidy))
      return false;
    if (!(sstype == rhs.sstype))
      return false;
    if (!(number == rhs.number))
      return false;
    return true;
  }
  bool operator != (const PoolOrder &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PoolOrder & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const PoolOrder& obj);
};

void swap(PoolOrder &a, PoolOrder &b);

typedef struct _Message__isset {
  _Message__isset() : template_type(false), push_type(false), app_type(false), title(false), content(false), text(false), url(false), target(false) {}
  bool template_type :1;
  bool push_type :1;
  bool app_type :1;
  bool title :1;
  bool content :1;
  bool text :1;
  bool url :1;
  bool target :1;
} _Message__isset;

class Message {
 public:

  static const char* ascii_fingerprint; // = "DE77150680E85FCEF44D37C23EABCA98";
  static const uint8_t binary_fingerprint[16]; // = {0xDE,0x77,0x15,0x06,0x80,0xE8,0x5F,0xCE,0xF4,0x4D,0x37,0xC2,0x3E,0xAB,0xCA,0x98};

  Message(const Message&);
  Message& operator=(const Message&);
  Message() : template_type(0), push_type(0), app_type(0), title(), content(), text(), url() {
  }

  virtual ~Message() throw();
  int32_t template_type;
  int32_t push_type;
  int32_t app_type;
  std::string title;
  std::string content;
  std::string text;
  std::string url;
  std::vector<std::string>  target;

  _Message__isset __isset;

  void __set_template_type(const int32_t val);

  void __set_push_type(const int32_t val);

  void __set_app_type(const int32_t val);

  void __set_title(const std::string& val);

  void __set_content(const std::string& val);

  void __set_text(const std::string& val);

  void __set_url(const std::string& val);

  void __set_target(const std::vector<std::string> & val);

  bool operator == (const Message & rhs) const
  {
    if (!(template_type == rhs.template_type))
      return false;
    if (!(push_type == rhs.push_type))
      return false;
    if (!(app_type == rhs.app_type))
      return false;
    if (!(title == rhs.title))
      return false;
    if (!(content == rhs.content))
      return false;
    if (!(text == rhs.text))
      return false;
    if (!(url == rhs.url))
      return false;
    if (!(target == rhs.target))
      return false;
    return true;
  }
  bool operator != (const Message &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Message & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Message& obj);
};

void swap(Message &a, Message &b);

} // namespace

#endif
