/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "order_constants.h"

namespace scheduler {

const orderConstants g_order_constants;

orderConstants::orderConstants() {
}

} // namespace

