/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef order_CONSTANTS_H
#define order_CONSTANTS_H

#include "order_types.h"

namespace scheduler {

class orderConstants {
 public:
  orderConstants();

};

extern const orderConstants g_order_constants;

} // namespace

#endif
